name: Notify Microsoft 365

on: [push] 

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Microsoft 365
      run: |
        curl -H "Content-Type: application/json" -d "{ 'text': '안녕하세요, 3팀 ~~!' }" https://o365kopo.webhook.office.com/webhookb2/ef331b30-9a42-4f8d-a0f8-875728660321@ad21525c-fc0f-4dbc-a403-67ce00add0e4/IncomingWebhook/d24e00f5868a4878b03212984e64a1ef/4682ea2a-90de-47c1-b354-fe564d7a0daf
